// These two variables are required to use React and to render it on the DOM.
import React from 'react';
import ReactDOM from 'react-dom';

// This is used to set up routing
import {Router, Route} from 'react-router';

// This package gets rid of ugly url bars generated by React
import { createHistory } from 'history';

var Hello = React.createClass({

  render: function() {
    return (
      <p> Hello World</p>
    )
  }
});

var routes = (
  <Router history={createHistory()} >
    <Route path="/" component={Hello} />
  </Router>
)

ReactDOM.render(routes, document.querySelector('#app'));
